{{- if .Values.secrets.useExternalSecrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: px-license-es
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: px-license
    template:
      type: Opaque
      engineVersion: v2
      data:
        license.lic: "{{ `{{ .dr_license }}` }}"
  data:
  - secretKey: dr_license
    remoteRef:
      key: secret/data/global/portworx
      property: dr-license
{{- end }}
